"""
AI助手SDK打包器
生成完整的AI助手JavaScript SDK代码
支持预览模式和灵童平台对接模式
"""

import json


def generate_ai_sdk_code(
    agent_id: str,
    name: str = "AI助手",
    avatar: str = None,
    greeting: str = "你好！有什么可以帮您的吗？",
    api_base_url: str = "/api/ai",
    theme_color: str = "#4F46E5",
    position: str = "right",
    bottom: int = 20,
    side_margin: int = 20,
    lingtong_api_url: str = None,
) -> str:
    """
    生成AI助手SDK代码（完整版）
    
    第三方嵌入方式：
    1. 粘贴配置代码，设置用户名
    2. 加载SDK脚本
    3. 自动初始化并渲染悬浮按钮
    """
    
    return f'''/* AI助手SDK - {name} */
/* Generated by SDK Share Platform */
(function() {{
    "use strict";
    
    const SDK_CONFIG = {{
        agentId: '{agent_id}',
        name: '{name}',
        greeting: {json.dumps(greeting)},
        themeColor: '{theme_color}',
        position: '{position}',
        bottom: {bottom},
        sideMargin: {side_margin},
        apiBaseUrl: window.AI_SDK_CONFIG?.apiBaseUrl || '{api_base_url}',
        userName: window.AI_SDK_CONFIG?.userName || '访客',
        lingtongApiUrl: window.AI_SDK_CONFIG?.lingtongApiUrl || '{lingtong_api_url or "/api/ai"}',
        lingtongToken: null,
        sessionToken: null,
        isInitialized: false,
        isLoading: false,
    }};
    
    // SDK样式
    const SDK_STYLES = `
        .ai-sdk-container * {{ margin: 0; padding: 0; box-sizing: border-box; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }}
        .ai-sdk-container {{ --theme-color: {theme_color}; position: fixed; z-index: 2147483647; bottom: {bottom}px; {position}: {side_margin}px; }}
        .ai-sdk-float-btn {{ width: 56px; height: 56px; border-radius: 50%; background: var(--theme-color); box-shadow: 0 4px 12px rgba(0,0,0,0.15); cursor: pointer; display: flex; align-items: center; justify-content: center; transition: transform 0.3s, box-shadow 0.3s; border: none; outline: none; }}
        .ai-sdk-float-btn:hover {{ transform: scale(1.1); box-shadow: 0 6px 20px rgba(0,0,0,0.2); }}
        .ai-sdk-float-btn svg {{ width: 28px; height: 28px; fill: white; }}
        .ai-sdk-window {{ position: absolute; bottom: 70px; {position}: 0; width: 380px; max-width: calc(100vw - 40px); height: 520px; max-height: calc(100vh - 120px); background: white; border-radius: 16px; box-shadow: 0 10px 40px rgba(0,0,0,0.2); display: none; flex-direction: column; overflow: hidden; animation: aiSdkSlideIn 0.3s ease; }}
        @keyframes aiSdkSlideIn {{ from {{ opacity: 0; transform: translateY(20px); }} to {{ opacity: 1; transform: translateY(0); }} }}
        .ai-sdk-header {{ padding: 16px; background: var(--theme-color); color: white; display: flex; align-items: center; gap: 12px; }}
        .ai-sdk-avatar {{ width: 40px; height: 40px; border-radius: 50%; background: rgba(255,255,255,0.2); display: flex; align-items: center; justify-content: center; overflow: hidden; }}
        .ai-sdk-avatar img {{ width: 100%; height: 100%; object-fit: cover; }}
        .ai-sdk-avatar svg {{ width: 24px; height: 24px; fill: white; }}
        .ai-sdk-info {{ flex: 1; }}
        .ai-sdk-name {{ font-weight: 600; font-size: 16px; }}
        .ai-sdk-status {{ font-size: 12px; opacity: 0.8; }}
        .ai-sdk-close {{ background: none; border: none; cursor: pointer; padding: 8px; border-radius: 8px; }}
        .ai-sdk-close:hover {{ background: rgba(255,255,255,0.2); }}
        .ai-sdk-close svg {{ width: 20px; height: 20px; fill: white; }}
        .ai-sdk-messages {{ flex: 1; overflow-y: auto; padding: 16px; background: #f5f5f5; display: flex; flex-direction: column; gap: 12px; }}
        .ai-sdk-message {{ max-width: 80%; padding: 12px 16px; border-radius: 16px; line-height: 1.5; word-break: break-word; }}
        .ai-sdk-message.user {{ align-self: flex-end; background: var(--theme-color); color: white; border-bottom-right-radius: 4px; }}
        .ai-sdk-message.assistant {{ align-self: flex-start; background: white; color: #333; border-bottom-left-radius: 4px; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }}
        .ai-sdk-time {{ font-size: 10px; color: #999; margin-top: 4px; }}
        .ai-sdk-input-area {{ padding: 12px 16px; background: white; border-top: 1px solid #eee; display: flex; gap: 8px; }}
        .ai-sdk-input {{ flex: 1; padding: 12px 16px; border: 1px solid #ddd; border-radius: 24px; outline: none; font-size: 14px; resize: none; max-height: 100px; }}
        .ai-sdk-input:focus {{ border-color: var(--theme-color); }}
        .ai-sdk-send {{ width: 44px; height: 44px; border: none; border-radius: 50%; background: var(--theme-color); cursor: pointer; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }}
        .ai-sdk-send:hover {{ opacity: 0.9; }}
        .ai-sdk-send:disabled {{ background: #ccc; cursor: not-allowed; }}
        .ai-sdk-send svg {{ width: 20px; height: 20px; fill: white; }}
        .ai-sdk-loading {{ display: flex; align-items: center; gap: 8px; padding: 12px 16px; background: white; border-radius: 16px; align-self: flex-start; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }}
        .ai-sdk-dots {{ display: flex; gap: 4px; }}
        .ai-sdk-dots span {{ width: 8px; height: 8px; background: #999; border-radius: 50%; animation: aiSdkBounce 1.4s infinite ease-in-out; }}
        .ai-sdk-dots span:nth-child(1) {{ animation-delay: 0s; }}
        .ai-sdk-dots span:nth-child(2) {{ animation-delay: 0.2s; }}
        .ai-sdk-dots span:nth-child(3) {{ animation-delay: 0.4s; }}
        @keyframes aiSdkBounce {{ 0%, 80%, 100% {{ transform: scale(0.6); opacity: 0.5; }} 40% {{ transform: scale(1); opacity: 1; }} }}
        .ai-sdk-welcome {{ text-align: center; padding: 40px 20px; color: #666; }}
        .ai-sdk-welcome-icon {{ width: 64px; height: 64px; margin: 0 auto 16px; background: var(--theme-color); border-radius: 50%; display: flex; align-items: center; justify-content: center; }}
        .ai-sdk-welcome-icon svg {{ width: 32px; height: 32px; fill: white; }}
    `;
    
    // 注入样式
    function injectStyles() {{
        if (document.getElementById('ai-sdk-styles')) return;
        const style = document.createElement('style');
        style.id = 'ai-sdk-styles';
        style.textContent = SDK_STYLES;
        document.head.appendChild(style);
    }}
    
    // 创建DOM结构
    function createDOM() {{
        if (document.getElementById('ai-sdk')) return;
        
        const container = document.createElement('div');
        container.id = 'ai-sdk';
        container.className = 'ai-sdk-container';
        container.innerHTML = `
            <button class="ai-sdk-float-btn" id="ai-sdk-btn">
                <svg viewBox="0 0 24 24"><path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H5.17L4 17.17V4h16v12z"/></svg>
            </button>
            <div class="ai-sdk-window" id="ai-sdk-window">
                <div class="ai-sdk-header">
                    <div class="ai-sdk-avatar">
                        {f'<img src="{avatar}" alt="avatar">' if avatar else '<svg viewBox="0 0 24 24"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 3c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zm0 14.2c-2.5 0-4.71-1.28-6-3.22.03-1.99 4-3.08 6-3.08 1.99 0 5.97 1.09 6 3.08-1.29 1.94-3.5 3.22-6 3.22z"/></svg>'}
                    </div>
                    <div class="ai-sdk-info">
                        <div class="ai-sdk-name">${{SDK_CONFIG.name}}</div>
                        <div class="ai-sdk-status">在线</div>
                    </div>
                    <button class="ai-sdk-close" id="ai-sdk-close">
                        <svg viewBox="0 0 24 24"><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/></svg>
                    </button>
                </div>
                <div class="ai-sdk-messages" id="ai-sdk-messages">
                    <div class="ai-sdk-welcome">
                        <div class="ai-sdk-welcome-icon">
                            <svg viewBox="0 0 24 24"><path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H5.17L4 17.17V4h16v12z"/></svg>
                        </div>
                        <p>${{SDK_CONFIG.greeting}}</p>
                    </div>
                </div>
                <div class="ai-sdk-input-area">
                    <textarea class="ai-sdk-input" id="ai-sdk-input" placeholder="输入消息..." rows="1"></textarea>
                    <button class="ai-sdk-send" id="ai-sdk-send">
                        <svg viewBox="0 0 24 24"><path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"/></svg>
                    </button>
                </div>
            </div>
        `;
        
        document.body.appendChild(container);
    }}
    
    // 初始化SDK
    async function initSDK() {{
        if (SDK_CONFIG.isInitialized) return;
        
        SDK_CONFIG.isInitialized = true;
        
        try {{
            // 调用托管平台初始化接口
            const resp = await fetch(SDK_CONFIG.apiBaseUrl + '/init?agent_id=' + encodeURIComponent(SDK_CONFIG.agentId) + '&user_name=' + encodeURIComponent(SDK_CONFIG.userName));
            const data = await resp.json();
            
            if (data.success) {{
                SDK_CONFIG.sessionToken = data.data.session_token;
                const config = data.data.agent_config || {{}};
                
                // 更新配置
                SDK_CONFIG.lingtongApiUrl = config.lingtongApiUrl || SDK_CONFIG.lingtongApiUrl;
                
                console.log('AI SDK初始化成功');
            }} else {{
                console.error('AI SDK初始化失败:', data.detail);
            }}
        }} catch (e) {{
            console.error('AI SDK初始化异常:', e);
        }}
    }}
    
    // 发送消息
    async function sendMessage(text) {{
        if (SDK_CONFIG.isLoading) return;
        SDK_CONFIG.isLoading = true;
        
        try {{
            // 优先使用灵童平台
            if (SDK_CONFIG.lingtongToken) {{
                const resp = await fetch(SDK_CONFIG.lingtongApiUrl + '/chat/message', {{
                    method: 'POST',
                    headers: {{
                        'Content-Type': 'application/json',
                        'Authorization': 'Bearer ' + SDK_CONFIG.lingtongToken
                    }},
                    body: JSON.stringify({{ message: text }})
                }});
                const data = await resp.json();
                if (data.success) return data.content;
                return data.error || '发送失败';
            }}
            
            // 使用托管平台接口
            const resp = await fetch(SDK_CONFIG.apiBaseUrl + '/message', {{
                method: 'POST',
                headers: {{ 'Content-Type': 'application/json' }},
                body: JSON.stringify({{
                    session_token: SDK_CONFIG.sessionToken,
                    message: text
                }})
            }});
            const data = await resp.json();
            if (data.success) return data.data.content;
            return data.detail || '发送失败';
        }} catch (e) {{
            console.error('发送消息异常:', e);
            return '网络错误';
        }} finally {{
            SDK_CONFIG.isLoading = false;
        }}
    }}
    
    // 绑定事件
    function bindEvents() {{
        const btn = document.getElementById('ai-sdk-btn');
        const window = document.getElementById('ai-sdk-window');
        const closeBtn = document.getElementById('ai-sdk-close');
        const input = document.getElementById('ai-sdk-input');
        const sendBtn = document.getElementById('ai-sdk-send');
        const messagesEl = document.getElementById('ai-sdk-messages');
        
        if (!btn || !window) return;
        
        btn.addEventListener('click', () => {{
            window.style.display = window.style.display === 'flex' ? 'none' : 'flex';
            if (window.style.display === 'flex') input.focus();
        }});
        
        closeBtn?.addEventListener('click', () => {{
            window.style.display = 'none';
        }});
        
        function formatTime(date) {{
            return date.toLocaleTimeString('zh-CN', {{ hour: '2-digit', minute: '2-digit' }});
        }}
        
        function addMessage(role, content) {{
            const msg = document.createElement('div');
            msg.className = 'ai-sdk-message ' + role;
            msg.innerHTML = content + '<div class="ai-sdk-time">' + formatTime(new Date()) + '</div>';
            messagesEl.appendChild(msg);
            messagesEl.scrollTop = messagesEl.scrollHeight;
        }}
        
        function showLoading() {{
            const loading = document.createElement('div');
            loading.className = 'ai-sdk-loading';
            loading.id = 'ai-sdk-loading';
            loading.innerHTML = '<div class="ai-sdk-dots"><span></span><span></span><span></span></div>';
            messagesEl.appendChild(loading);
            messagesEl.scrollTop = messagesEl.scrollHeight;
        }}
        
        function hideLoading() {{
            const loading = document.getElementById('ai-sdk-loading');
            if (loading) loading.remove();
        }}
        
        async function handleSend() {{
            const text = input.value.trim();
            if (!text || SDK_CONFIG.isLoading) return;
            
            addMessage('user', text);
            input.value = '';
            input.style.height = 'auto';
            showLoading();
            
            const response = await sendMessage(text);
            hideLoading();
            addMessage('assistant', response);
        }}
        
        sendBtn?.addEventListener('click', handleSend);
        input?.addEventListener('keydown', (e) => {{
            if (e.key === 'Enter' && !e.shiftKey) {{
                e.preventDefault();
                handleSend();
            }}
        }});
        input?.addEventListener('input', function() {{
            this.style.height = 'auto';
            this.style.height = Math.min(this.scrollHeight, 100) + 'px';
        }});
    }}
    
    // 启动SDK
    function start() {{
        injectStyles();
        createDOM();
        bindEvents();
        
        // 获取配置
        if (window.AI_SDK_CONFIG) {{
            SDK_CONFIG.userName = window.AI_SDK_CONFIG.userName || SDK_CONFIG.userName;
            SDK_CONFIG.apiBaseUrl = window.AI_SDK_CONFIG.apiBaseUrl || SDK_CONFIG.apiBaseUrl;
            SDK_CONFIG.lingtongApiUrl = window.AI_SDK_CONFIG.lingtongApiUrl || SDK_CONFIG.lingtongApiUrl;
        }}
        
        // 自动初始化
        if (document.readyState === 'loading') {{
            document.addEventListener('DOMContentLoaded', initSDK);
        }} else {{
            initSDK();
        }}
    }}
    
    // 暴露全局接口
    window.__AI_SDK__ = {{
        init: initSDK,
        sendMessage: sendMessage,
        config: SDK_CONFIG,
    }};
    
    start();
}})();
'''


def generate_ai_sdk_embed_code(
    agent_id: str,
    name: str = "AI助手",
    **kwargs
) -> dict:
    """
    生成AI助手SDK嵌入代码
    
    Returns:
        包含配置代码和SDK代码的字典
    """
    
    sdk_code = generate_ai_sdk_code(agent_id, name, **kwargs)
    
    # 配置代码
    config_code = f'''<!-- AI助手SDK配置（必须放在SDK脚本之前）-->
<script>
window.AI_SDK_CONFIG = {{
    // Agent ID
    agentId: '{agent_id}',
    
    // 助手名称
    name: '{name}',
    
    // 用户名（第三方透传）- 必须设置
    userName: '',
    
    // API基础路径
    apiBaseUrl: '/api/ai',
    
    // 灵童平台API地址（可选）
    lingtongApiUrl: '',
    
    // 主题色
    themeColor: '{kwargs.get("theme_color", "#4F46E5")}',
    
    // 位置
    position: '{kwargs.get("position", "right")}',
    
    // 底部距离
    bottom: {kwargs.get("bottom", 20)},
    
    // 侧边距离
    sideMargin: {kwargs.get("side_margin", 20)}
}};
</script>'''

    # SDK代码
    sdk_script = f'''<!-- AI助手SDK脚本 -->
<script src="/api/sdk/ai/{agent_id}/embed"></script>'''

    return {
        "config": config_code,
        "sdk": sdk_script,
        "full": f'''{config_code}

{sdk_script}

<!-- 设置用户名（示例） -->
<script>
// 从业务系统获取用户名后设置
if (window.AI_SDK_CONFIG) {{
    window.AI_SDK_CONFIG.userName = '当前用户名'; // 必填
    // 重新初始化
    if (window.__AI_SDK__) {{
        window.__AI_SDK__.init();
    }}
}}
</script>''',
        "code": sdk_code
    }
